/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aldrin.cafsys.gui.dialog;

import com.aldrin.cafsys.api.ComboBoxList;
import com.aldrin.cafsys.gui.dialog.au.db.AppQuery;
import com.aldrin.cafsys.model.Menu;
import java.awt.AlphaComposite;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Blob;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Java Programming with Aldrin
 */


public class JDialogUpdatePrice extends javax.swing.JDialog {

    private com.aldrin.cafsys.gui.JFrameCafSys mainMenu;
    private String evt = new String();
    private File pictureFile = null;
    private File photo;
    private Menu menu = new Menu();
    private AppQuery query = new AppQuery();

    /**
     * Creates new form JDialogSupplierAUD
     */
    public JDialogUpdatePrice(com.aldrin.cafsys.gui.JFrameCafSys parent, boolean modal) {
        super(parent, modal);
        this.mainMenu = parent;
        initComponents();
        comboBoxCategory();
    }

    public JDialogUpdatePrice(com.aldrin.cafsys.gui.JFrameCafSys parent, boolean modal, String evtl) {
        super(parent, modal);
        initComponents();
        comboBoxCategory();
        this.evt = evtl;
        setTitle("Add Category");
        jButtonSave.setText("Save");
        jButtonSave.setMnemonic('S');

    }

    public JDialogUpdatePrice(com.aldrin.cafsys.gui.JFrameCafSys parent, boolean modal, String evtl, Menu menu) {
        super(parent, modal);
        initComponents();
        comboBoxCategory();
        this.evt = evtl;
        this.menu = menu;
        this.setTitle("Update category");
        jButtonSave.setText("Update");
        jButtonSave.setMnemonic('U');
        jTextFieldMenu.setText(this.menu.getMenu());
        jTextFieldPrice.setText(String.valueOf(this.menu.getPrice()));
        jTextAreaIngredients.setText(this.menu.getIngredient());
        if (query.selectedMenuPicture(menu) == null) {
            jLabelPicture.setIcon(null);
            return;
        } else {
            jLabelPicture.setText(null);
            displayPicture();
        }
        for (ComboBoxList a : this.query.getList()) {
            a.setSelectedId(query.getList(), String.valueOf(this.menu.getCategory().getId()), jComboBoxCategory);
        }

    }

    public JDialogUpdatePrice(com.aldrin.cafsys.gui.JFrameCafSys parent, boolean modal, Menu menu, String evtl) {
        super(parent, modal);
        initComponents();
        this.setTitle("Delete category");
        comboBoxCategory();
        this.evt = evtl;
        this.menu = menu;
        jButtonSave.setText("Delete");
        jButtonSave.setMnemonic('D');
        jTextFieldMenu.setText(this.menu.getMenu());
        jTextFieldPrice.setText(String.valueOf(this.menu.getPrice()));
        jTextAreaIngredients.setText(this.menu.getIngredient());
        if (query.selectedMenuPicture(menu) == null) {
            jLabelPicture.setIcon(null);
            return;
        } else {
            jLabelPicture.setText(null);
            displayPicture();
        }
        for (ComboBoxList a : this.query.getList()) {
            a.setSelectedId(query.getList(), String.valueOf(this.menu.getCategory().getId()), jComboBoxCategory);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaIngredients = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMenu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxCategory = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabelPicture = new javax.swing.JLabel();
        jPanelButton = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update price");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setText("Category");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, -1));

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel4.setText("Ingredients");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, -1));

        jTextFieldPrice.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, 270, 30));

        jTextAreaIngredients.setEditable(false);
        jTextAreaIngredients.setColumns(20);
        jTextAreaIngredients.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextAreaIngredients.setRows(5);
        jTextAreaIngredients.setFocusable(false);
        jScrollPane1.setViewportView(jTextAreaIngredients);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 480, 120));

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel5.setText("Price");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 180, -1));

        jTextFieldMenu.setEditable(false);
        jTextFieldMenu.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextFieldMenu.setFocusable(false);
        jPanel2.add(jTextFieldMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 270, 30));

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel6.setText("Menu");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, -1));

        jComboBoxCategory.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jComboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCategory.setEnabled(false);
        jComboBoxCategory.setFocusable(false);
        jPanel2.add(jComboBoxCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 270, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabelPicture.setBackground(new java.awt.Color(153, 153, 153));
        jLabelPicture.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabelPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPicture.setText("No Photo");
        jLabelPicture.setFocusable(false);
        jLabelPicture.setMaximumSize(new java.awt.Dimension(200, 160));
        jLabelPicture.setMinimumSize(new java.awt.Dimension(200, 160));
        jLabelPicture.setOpaque(true);
        jLabelPicture.setPreferredSize(new java.awt.Dimension(200, 160));
        jLabelPicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPictureMouseClicked(evt);
            }
        });
        jPanel3.add(jLabelPicture, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 200, 160));

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanelButton.setPreferredSize(new java.awt.Dimension(394, 60));
        jPanelButton.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(204, 204, 204)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSave.setMnemonic('S');
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 100, 36));

        jPanelButton.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setPreferredSize(new java.awt.Dimension(10, 100));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanelButton.add(jPanel6, java.awt.BorderLayout.WEST);

        jPanel7.setPreferredSize(new java.awt.Dimension(10, 100));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanelButton.add(jPanel7, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanelButton, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(519, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        try {
            int response = JOptionPane.showConfirmDialog(this, "Are you sure to change price?", "Price confirmation!!", JOptionPane.WARNING_MESSAGE);
            if (response == JOptionPane.YES_OPTION) {
                new JDialogMenuOfTheDay(Double.parseDouble(jTextFieldPrice.getText()));
                query.updateMenuPrice(Double.parseDouble(jTextFieldPrice.getText()), menu.getId());
                this.dispose();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jLabelPictureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPictureMouseClicked
        browse();
    }//GEN-LAST:event_jLabelPictureMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<Object> jComboBoxCategory;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelPicture;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaIngredients;
    private javax.swing.JTextField jTextFieldMenu;
    private javax.swing.JTextField jTextFieldPrice;
    // End of variables declaration//GEN-END:variables
private void comboBoxCategory() {
        this.jComboBoxCategory.removeAllItems();
        query.categoryComboBox();
        for (ComboBoxList a : query.getList()) {
            this.jComboBoxCategory.addItem(a);
        }
    }

    private void browse() {
        try {
            int returnVal = jFileChooser1.showOpenDialog(this);

            if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
                pictureFile = jFileChooser1.getSelectedFile();

                int IMG_WIDTH = jLabelPicture.getWidth();
                int IMG_HEIGHT = jLabelPicture.getHeight();

                try {
                    BufferedImage originalImage = ImageIO.read(pictureFile);
                    int type = originalImage.getType() == 0 ? BufferedImage.TYPE_INT_ARGB : originalImage.getType();

                    BufferedImage resizedImage = new BufferedImage(IMG_WIDTH, IMG_HEIGHT, type);
                    Graphics2D g = resizedImage.createGraphics();
                    g.drawImage(originalImage, 0, 0, IMG_WIDTH, IMG_HEIGHT, null);
                    g.dispose();
                    g.setComposite(AlphaComposite.Src);

                    g.setRenderingHint(RenderingHints.KEY_INTERPOLATION,
                            RenderingHints.VALUE_INTERPOLATION_BILINEAR);
                    g.setRenderingHint(RenderingHints.KEY_RENDERING,
                            RenderingHints.VALUE_RENDER_QUALITY);
                    g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                            RenderingHints.VALUE_ANTIALIAS_ON);

                    jLabelPicture.setIcon(new ImageIcon(resizedImage)); //to eliminate .jpeg from picture filename
                    ImageIO.write(resizedImage, "png", new File("src\\cafsys\\images\\model.jpg"));

                } catch (final IOException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Opss...", JOptionPane.ERROR_MESSAGE);
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void displayPicture() {
        try {
            Blob blobImage = (Blob) query.selectedMenuPicture(menu);
            ImageIcon icon = new ImageIcon(blobImage.getBytes(1L, (int) blobImage.length()));

            Image image = icon.getImage();

            int IMG_WIDTH = 200;
            int IMG_HEIGHT = 160;
            int type = BufferedImage.TYPE_INT_ARGB;

            BufferedImage resizedImage = new BufferedImage(IMG_WIDTH, IMG_HEIGHT, type);
            Graphics2D g = resizedImage.createGraphics();
            g.drawImage(image, 0, 0, IMG_WIDTH, IMG_HEIGHT, null);
            g.dispose();
            g.setComposite(AlphaComposite.Src);

            g.setRenderingHint(RenderingHints.KEY_INTERPOLATION,
                    RenderingHints.VALUE_INTERPOLATION_BILINEAR);
            g.setRenderingHint(RenderingHints.KEY_RENDERING,
                    RenderingHints.VALUE_RENDER_QUALITY);
            g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);

            jLabelPicture.setIcon(new ImageIcon(resizedImage));//image to label

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
