/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aldrin.cafsys.gui.dialog.au;

import com.aldrin.cafsys.api.ComboBoxList;
import com.aldrin.cafsys.gui.dialog.au.db.AppQuery;
import com.aldrin.cafsys.model.Category;
import com.aldrin.cafsys.model.Menu;
import java.awt.AlphaComposite;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Blob;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Java Programming with Aldrin
 */

public class JDialogMenuOfTheDayAU extends javax.swing.JDialog {

    private com.aldrin.cafsys.gui.JFrameCafSys mainMenu;
    private String evt = new String();
    private File pictureFile = null;
    private File photo;
    private Menu menu = new Menu();
    private AppQuery query = new AppQuery();

    /**
     * Creates new form JDialogSupplierAUD
     */
    public JDialogMenuOfTheDayAU(com.aldrin.cafsys.gui.JFrameCafSys parent, boolean modal) {
        super(parent, modal);
        this.mainMenu = parent;
        initComponents();
        comboBoxCategory();
    }

    public JDialogMenuOfTheDayAU(com.aldrin.cafsys.gui.JFrameCafSys parent, boolean modal, String evtl) {
        super(parent, modal);
        initComponents();
        comboBoxCategory();
        this.evt = evtl;
        setTitle("Add Category");
        jButtonSave.setText("Save");
        jButtonSave.setMnemonic('S');

    }

    public JDialogMenuOfTheDayAU(com.aldrin.cafsys.gui.JFrameCafSys parent, boolean modal, String evtl, Menu menu) {
        super(parent, modal);
        initComponents();
        this.evt = evtl;
        this.menu = menu;
        jButtonSave.setText("Update");
        jButtonSave.setMnemonic('U');
        jTextFieldMenu.setText(this.menu.getMenu());
        if (query.selectedMenuPicture(menu) == null) {
            jLabelPicture.setIcon(null);
            return;
        } else {
            jLabelPicture.setText(null);
            displayPicture();
        }

    }

    public JDialogMenuOfTheDayAU(com.aldrin.cafsys.gui.JFrameCafSys parent, boolean modal, Menu menu, String evtl) {
        super(parent, modal);
        initComponents();
        this.evt = evtl;
        this.menu = menu;
        jButtonSave.setText("Delete");
        jButtonSave.setMnemonic('D');
        jTextFieldMenu.setText(this.menu.getMenu());
        if (query.selectedMenuPicture(menu) == null) {
            jLabelPicture.setIcon(null);
            return;
        } else {
            jLabelPicture.setText(null);
            displayPicture();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMenu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxCategory = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabelPicture = new javax.swing.JLabel();
        jPanelButton = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setText("Menu");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, -1));

        jTextFieldMenu.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 270, 30));

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel6.setText("Price");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, 180, -1));

        jComboBoxCategory.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jComboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBoxCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 270, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabelPicture.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabelPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPicture.setText("No Photo");
        jLabelPicture.setMaximumSize(new java.awt.Dimension(200, 160));
        jLabelPicture.setMinimumSize(new java.awt.Dimension(200, 160));
        jLabelPicture.setPreferredSize(new java.awt.Dimension(200, 160));
        jLabelPicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPictureMouseClicked(evt);
            }
        });
        jPanel3.add(jLabelPicture, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 120, 100));

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanelButton.setPreferredSize(new java.awt.Dimension(394, 60));
        jPanelButton.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(204, 204, 204)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSave.setMnemonic('S');
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 100, 36));

        jPanelButton.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setPreferredSize(new java.awt.Dimension(10, 100));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanelButton.add(jPanel6, java.awt.BorderLayout.WEST);

        jPanel7.setPreferredSize(new java.awt.Dimension(10, 100));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanelButton.add(jPanel7, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanelButton, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(438, 231));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        try {
            ComboBoxList courseIdl = (ComboBoxList) this.jComboBoxCategory.getSelectedItem();
            Category c = new Category();
            c.setId(Integer.parseInt(courseIdl.getId()));
            menu.setCategory(c);
            switch (this.evt) {

                case "Add":
                    if ((jTextFieldMenu.getText().isEmpty() == true) || (jTextFieldMenu.getText().isEmpty() == true) || (jTextFieldMenu.getText().isEmpty() == true)) {
                        JOptionPane.showMessageDialog(mainMenu, "Empty fields is not allowed!", "Warining!!", JOptionPane.PLAIN_MESSAGE);
                        return;
                    } else {
                        menu.setMenu(jTextFieldMenu.getText());
                        menu.setPrice(Double.parseDouble(jTextFieldMenu.getText()));
                        menu.setIngredient(jTextFieldMenu.getText());
                    }
                    int reply = JOptionPane.showConfirmDialog(this,
                            "Are you sure  to save " + jTextFieldMenu.getText() + "   " + jTextFieldMenu.getText() + " ?",
                            "Confirmation - Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
                    if (reply == JOptionPane.YES_OPTION) {
                        try {
                            if (pictureFile == null) {
                                int response = JOptionPane.showConfirmDialog(this,
                                        "Are you sure  to save " + jTextFieldMenu.getText() + " without picture?",
                                        "Student Confirmation - Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
                                if (response == JOptionPane.YES_OPTION) {
                                    menu.setPhoto(new File(System.getProperty("user.dir") + "/src/cafsys/images/no photo.jpg"));
                                    new AppQuery().addMenu(menu);
                                    JOptionPane.showConfirmDialog(null, "You're saving without picture", "Message", JOptionPane.PLAIN_MESSAGE);
                                }
                            } else {
                                menu.setPhoto(new File(System.getProperty("user.dir") + "/src/cafsys/images/model.jpg"));
                                int response = JOptionPane.showConfirmDialog(this,
                                        "Are you sure  to save " + jTextFieldMenu.getText() + " ?",
                                        "Student Confirmation - Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
                                if (response == JOptionPane.YES_OPTION) {

                                    new AppQuery().addMenu(menu);
                                } else if (response == JOptionPane.NO_OPTION) {
                                    System.out.print("");
                                }
                            }
                        } catch (Exception e) {
                            e.printStackTrace();
                        }

                    } else if (reply == JOptionPane.NO_OPTION) {

                    }
                    this.dispose();
                    break;

                case "Update":
                    int upate = JOptionPane.showConfirmDialog(this,
                            "Are you sure  to save " + jTextFieldMenu.getText() + "   " + jTextFieldMenu.getText() + " ?",
                            "Confirmation - Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
                    if (upate == JOptionPane.YES_OPTION) {
//                        menu.setCategory(jTextFieldPrice.getText());
//                        menu.setDescription(jTextAreaIngredients.getText());
//                        new AppQuery().updateCategory(menu);
                    }
                    this.dispose();
                    break;
                case "Delete":
                    int response = JOptionPane.showConfirmDialog(null, "Are you sure to delete " + menu.getCategory() + " " + menu.getPrice() + " ?", "Delete Confirmation!!", JOptionPane.YES_NO_OPTION);
                    if (response == JOptionPane.YES_OPTION) {
//                        new AppQuery().deleteCategory(menu);
//                        JOptionPane.showMessageDialog(null, menu.getCategory() + " " + menu.getDescription() + " is successfully deleted.", "Message", JOptionPane.PLAIN_MESSAGE);
                    }
                    this.dispose();
                    break;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jLabelPictureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPictureMouseClicked
        browse();
    }//GEN-LAST:event_jLabelPictureMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<Object> jComboBoxCategory;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelPicture;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JTextField jTextFieldMenu;
    // End of variables declaration//GEN-END:variables
private void comboBoxCategory() {
        this.jComboBoxCategory.removeAllItems();
        query.menuComboBox();
        for (ComboBoxList a : query.getList()) {
            this.jComboBoxCategory.addItem(a);
        }
    }

    private void browse() {
        try {
            int returnVal = jFileChooser1.showOpenDialog(this);

            if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
                pictureFile = jFileChooser1.getSelectedFile();

                int IMG_WIDTH = jLabelPicture.getWidth();
                int IMG_HEIGHT = jLabelPicture.getHeight();

                try {
                    BufferedImage originalImage = ImageIO.read(pictureFile);
                    int type = originalImage.getType() == 0 ? BufferedImage.TYPE_INT_ARGB : originalImage.getType();

                    BufferedImage resizedImage = new BufferedImage(IMG_WIDTH, IMG_HEIGHT, type);
                    Graphics2D g = resizedImage.createGraphics();
                    g.drawImage(originalImage, 0, 0, IMG_WIDTH, IMG_HEIGHT, null);
                    g.dispose();
                    g.setComposite(AlphaComposite.Src);

                    g.setRenderingHint(RenderingHints.KEY_INTERPOLATION,
                            RenderingHints.VALUE_INTERPOLATION_BILINEAR);
                    g.setRenderingHint(RenderingHints.KEY_RENDERING,
                            RenderingHints.VALUE_RENDER_QUALITY);
                    g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                            RenderingHints.VALUE_ANTIALIAS_ON);

                    jLabelPicture.setIcon(new ImageIcon(resizedImage)); //to eliminate .jpeg from picture filename
                    ImageIO.write(resizedImage, "png", new File("src\\cafsys\\images\\model.jpg"));

                } catch (final IOException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Opss...", JOptionPane.ERROR_MESSAGE);
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void displayPicture() {
        try {
            Blob blobImage = (Blob) query.selectedMenuPicture(menu);
            ImageIcon icon = new ImageIcon(blobImage.getBytes(1L, (int) blobImage.length()));

            Image image = icon.getImage();

            int IMG_WIDTH = 200;
            int IMG_HEIGHT = 160;
            int type = BufferedImage.TYPE_INT_ARGB;

            BufferedImage resizedImage = new BufferedImage(IMG_WIDTH, IMG_HEIGHT, type);
            Graphics2D g = resizedImage.createGraphics();
            g.drawImage(image, 0, 0, IMG_WIDTH, IMG_HEIGHT, null);
            g.dispose();
            g.setComposite(AlphaComposite.Src);

            g.setRenderingHint(RenderingHints.KEY_INTERPOLATION,
                    RenderingHints.VALUE_INTERPOLATION_BILINEAR);
            g.setRenderingHint(RenderingHints.KEY_RENDERING,
                    RenderingHints.VALUE_RENDER_QUALITY);
            g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);

            jLabelPicture.setIcon(new ImageIcon(resizedImage));//image to label

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
