/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aldrin.cafsys.gui;

import com.aldrin.cafsys.api.PanelSwaper;
import com.aldrin.cafsys.gui.dialog.JDialogCategory;
import com.aldrin.cafsys.gui.dialog.JDialogChangePassword;
import com.aldrin.cafsys.gui.dialog.JDialogLogin;
import com.aldrin.cafsys.gui.dialog.JDialogMenu;
import com.aldrin.cafsys.gui.dialog.JDialogMenuOfTheDay;
import com.aldrin.cafsys.gui.dialog.JDialogSalesUser;
import com.aldrin.cafsys.gui.dialog.JDialogUser;
import com.aldrin.cafsys.gui.dialog.JDialogViewInvoice;
import com.aldrin.cafsys.gui.dialog.au.db.AppQuery;
import com.aldrin.cafsys.gui.dialog.au.db.LoginUser;
import com.aldrin.cafsys.gui.panel.JPanelCashier;
import com.aldrin.cafsys.reports.JDialogSalesUserReports;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Java Programming with Aldrin
 */
public class JFrameCafSys extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCafSys
     */
    private static JPanelCashier panelCashier = new JPanelCashier();
    private AppQuery query = new AppQuery();
    private static Integer categoryId;
    private static boolean logIn = false;

    public JFrameCafSys() {
        initComponents();
        panelCashier.setMainJFrame(this);
        this.jMenuItemExit.addActionListener(new com.aldrin.cafsys.events.ActionListenerHandler());
        jPanelRootPanel.add(new PanelSwaper(panelCashier));
        panelCashier.clickTable();
        logIn();
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent we) {
                quitApp();
            }
        });

    }

    public JFrameCafSys(JPanelCashier panelCashier) {
        initComponents();
        panelCashier.selectMenu();
        panelCashier.jPanelShowMenu.validate();
        jPanelRootPanel.add(new PanelSwaper(panelCashier));
        jPanelRootPanel.validate();
        jPanelRootPanel.updateUI();
        updateContainer();
        this.getContentPane().validate();

    }

    public JFrameCafSys(JPanelCashier panelCashier, com.aldrin.cafsys.model.MOTD m) {
        //
        initComponents();
        panelCashier.jPanelShowMenu.validate();
        jPanelRootPanel.add(new PanelSwaper(panelCashier));
        jPanelRootPanel.validate();
        jPanelRootPanel.updateUI();
        updateContainer();
        this.panelCashier.addOrderToTable(m);
        this.panelCashier.autoCalulateTable();
        this.getContentPane().validate();
    }

    public JFrameCafSys(JPanelCashier panelCashier, String holdOrder) {
        initComponents();
        panelCashier.jPanelShowMenu.validate();
        jPanelRootPanel.add(new PanelSwaper(panelCashier));
        jPanelRootPanel.validate();
        jPanelRootPanel.updateUI();
        updateContainer();
        if (holdOrder.equals("Hold")) {
            this.panelCashier.hold();
        } else {
            this.panelCashier.release();
        }
        this.panelCashier.autoCalulateTable();
        this.getContentPane().validate();
    }

    public JFrameCafSys(JPanelCashier panelCashier, Boolean removeMenu) {
        initComponents();
        panelCashier.selectMenu();
        panelCashier.jPanelShowMenu.validate();
        jPanelRootPanel.add(new PanelSwaper(panelCashier));
        jPanelRootPanel.validate();
        jPanelRootPanel.updateUI();
        updateContainer();
        this.panelCashier.autoCalulateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRootPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUser = new javax.swing.JMenu();
        jMenuItemLogOut = new javax.swing.JMenuItem();
        jMenuItemLogIN = new javax.swing.JMenuItem();
        jMenuItemChangePassword = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuAdministration = new javax.swing.JMenu();
        jMenuItemUser = new javax.swing.JMenuItem();
        jMenuItemCategory = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuSales = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuView = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuReport = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CafSys POS");
        setIconImage(Toolkit.getDefaultToolkit().getImage(JDialogUser.class.getResource("/images/c.png")));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanelRootPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanelRootPanel, java.awt.BorderLayout.CENTER);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(600, 30));

        jMenuUser.setText("File");
        jMenuUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuUser.setOpaque(true);
        jMenuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUserActionPerformed(evt);
            }
        });

        jMenuItemLogOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemLogOut.setText("Logout");
        jMenuItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogOutActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItemLogOut);

        jMenuItemLogIN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemLogIN.setText("Login");
        jMenuItemLogIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogINActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItemLogIN);

        jMenuItemChangePassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemChangePassword.setText("Change Password");
        jMenuItemChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemChangePasswordActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItemChangePassword);
        jMenuUser.add(jSeparator1);

        jMenuItemExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItemExit);

        jMenuBar1.add(jMenuUser);

        jMenuAdministration.setText("Administration");
        jMenuAdministration.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItemUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemUser.setText("User");
        jMenuItemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUserActionPerformed(evt);
            }
        });
        jMenuAdministration.add(jMenuItemUser);

        jMenuItemCategory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemCategory.setText("Category");
        jMenuItemCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCategoryActionPerformed(evt);
            }
        });
        jMenuAdministration.add(jMenuItemCategory);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem4.setText("Menu");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuAdministration.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem5.setText("Menu of the Day");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuAdministration.add(jMenuItem5);

        jMenuBar1.add(jMenuAdministration);

        jMenuSales.setText("Sales");
        jMenuSales.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem7.setText("User");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenuSales.add(jMenuItem7);

        jMenuBar1.add(jMenuSales);

        jMenuView.setText("View");
        jMenuView.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem6.setText("Invoice");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuView.add(jMenuItem6);

        jMenuBar1.add(jMenuView);

        jMenuReport.setText("Report");
        jMenuReport.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem9.setText("User Sales");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenuReport.add(jMenuItem9);

        jMenuBar1.add(jMenuReport);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1385, 738));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        quitApp();
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogOutActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure to log-out?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            setLogIn(false);
            new LoginUser().setUser(null);
        }
        if (isLogIn() == true) {
            logIn();
        } else {
            logOut();
        }
    }//GEN-LAST:event_jMenuItemLogOutActionPerformed

    private void jMenuItemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUserActionPerformed
        JDialogUser user = new JDialogUser(this, true);
        user.setVisible(true);
    }//GEN-LAST:event_jMenuItemUserActionPerformed

    private void jMenuItemCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCategoryActionPerformed
        JDialogCategory category = new JDialogCategory(this, true);
        category.setVisible(true);
        panelCashier.selectCategory();

    }//GEN-LAST:event_jMenuItemCategoryActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JDialogMenu menu = new JDialogMenu(this, true);
        menu.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JDialogMenuOfTheDay mofd = new JDialogMenuOfTheDay(this, true);
        mofd.setVisible(true);
        panelCashier.selectCategory();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JDialogViewInvoice viewInvoice = new JDialogViewInvoice(this, true);
        viewInvoice.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        JDialogSalesUser su = new JDialogSalesUser(this, true);
        su.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        JDialogSalesUserReports usr = new JDialogSalesUserReports(this, true);
        usr.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItemLogINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogINActionPerformed
        JDialogLogin login = new JDialogLogin(this, true);
        login.setVisible(true);
        if (isLogIn() == true) {
            logIn();
        } else {
            logOut();
        }

    }//GEN-LAST:event_jMenuItemLogINActionPerformed

    private void jMenuItemChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemChangePasswordActionPerformed
        JDialogChangePassword cp = new JDialogChangePassword(this, true);
        cp.setVisible(true);
    }//GEN-LAST:event_jMenuItemChangePasswordActionPerformed

    private void jMenuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuUserActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAdministration;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemCategory;
    private javax.swing.JMenuItem jMenuItemChangePassword;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLogIN;
    private javax.swing.JMenuItem jMenuItemLogOut;
    private javax.swing.JMenuItem jMenuItemUser;
    private javax.swing.JMenu jMenuReport;
    private javax.swing.JMenu jMenuSales;
    private javax.swing.JMenu jMenuUser;
    private javax.swing.JMenu jMenuView;
    private javax.swing.JPanel jPanelRootPanel;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
    public void updateContainer() {
        panelCashier.selectMenu();
    }

    public void logIn() {
        setLogIn(true);
        jMenuAdministration.setEnabled(true);
        jMenuSales.setEnabled(true);
        jMenuView.setEnabled(true);
        jMenuReport.setEnabled(true);
        jMenuItemLogIN.setVisible(false);
        jMenuItemChangePassword.setVisible(true);
        jMenuItemLogOut.setVisible(true);
        jMenuUser.setText(new LoginUser().getUser().getFirstname() + " " + new LoginUser().getUser().getMiddlename().substring(0, 1) + ". " + new LoginUser().getUser().getLastname());
        panelCashier.logIn();
    }

    public void logOut() {
        jMenuAdministration.setEnabled(false);
        jMenuSales.setEnabled(false);
        jMenuView.setEnabled(false);
        jMenuReport.setEnabled(false);
        jMenuItemLogIN.setVisible(true);
        jMenuItemChangePassword.setVisible(false);
        jMenuItemLogOut.setVisible(false);
        jMenuUser.setText("System");
        panelCashier.logOut();

    }

    /**
     * @return the logIn
     */
    public static boolean isLogIn() {
        return logIn;
    }

    /**
     * @param aLogIn the logIn to set
     */
    public static void setLogIn(boolean aLogIn) {
        logIn = aLogIn;
    }

    private void quitApp() {
        try {
            int reply = JOptionPane.showConfirmDialog(this,
                    "Are you sure to exit Cafsys application?",
                    "CafSys Point of Sale - Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                System.exit(0);        //Close the Application.
            } else if (reply == JOptionPane.NO_OPTION) {
                setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            }
        } catch (Exception e) {
        }

    }

}
